name: On Label
on:
  issues:
    types: [labeled]

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Process Label Action
        uses: hramos/label-actions@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
