name: On PR Open
on:
  pull_request:
    branches:
      - release/**
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2
      with:
        repository: 'microsoft/vscode-github-triage-actions'
        path: ./actions
        ref: v42
    - name: Install Actions
      run: npm install --production --prefix ./actions
    - name: Run Commands
      uses: ./actions/commands
      with:
        config-path: port-request-commands.json


